name: tpad-text-editor
title: Tpad
base: core24
version: '7.3.0.0'
summary: Simple text editor
description: |
  A simple, easy to use, fast text editor.

website: https://launchpad.net/tpad-project
source-code: https://git.launchpad.net/tpad-project
issues: https://bugs.launchpad.net/tpad-project
contact: https://bugs.launchpad.net/tpad-project
license: GPL-3.0+
icon: icon/tpad_128.png

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:

apps:
  tpad:
    command: usr/bin/tpad
    desktop: usr/share/applications/tpad.desktop
    extensions:
      - gnome
    plugs:
      - cups
      - home

parts:
  tpad:
    plugin: autotools
    source: .
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - autoconf
      - automake
      - intltool
      - libgtk-4-dev
      - libgtksourceview-5-dev
      - libspelling-1-dev
      - libtool
    override-build: |
      autoreconf --force --install
      craftctl default
    stage-packages:
      - libgtksourceview-5-0
      - libspelling-1-1
