name: tpad-text-editor
title: Tpad
base: core24
version: '7.2.0.1'
summary: Simple text editor
description: |
  A simple, easy to use, fast text editor.

website: https://launchpad.net/tpad-project
source-code: https://git.launchpad.net/tpad-project
issues: https://bugs.launchpad.net/tpad-project
contact: https://bugs.launchpad.net/tpad-project
license: GPL-3.0+
icon: usr/share/icons/tpad.png

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:

apps:
  tpad:
    command: usr/bin/tpad
    desktop: usr/share/applications/tpad.desktop
    extensions:
      - gnome
    plugs:
      - cups
      - home

parts:
  tpad:
    plugin: autotools
    source: https://git.launchpad.net/tpad-project
    source-type: git
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - intltool
      - libgtkspell3-3-dev
      - libgtksourceview-3.0-dev
    stage-packages:
      - libgtkspell3-3-0
