name: tpad-text-editor # use the same name as the package
base: core24 # core24 is current, snapcraft.io/core24, the base snap is the execution environment for this snap
version: '7.0.0.4-2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple text editor
description: |
   A simple, easy to use, fast text editor.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  desktop:
  desktop-legacy:
  wayland:
  x11:
  home:
  gsettings:
  unity7:

parts:
  tpad:
    # See 'snapcraft plugins'
    plugin: autotools
    autotools-configure-parameters: ["--prefix=/usr"]
    source: git://git.launchpad.net/tpad-project
    build-packages:
      - autoconf
      - automake
      - build-essential
      - libgtksourceview-3.0-dev
      - uuid-dev
      - libuuid1
      - libgtkspell3-3-dev
      - libgtk-3-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libatk1.0-dev
      - libgucharmap-2-90-dev
      - gucharmap
      - libpixman-1-dev
      - libcairo-gobject2
      - libsystemd-dev
      - libpthread-stubs0-dev
      - libicu-dev
      - cdbs
      - debhelper
      - intltool
    stage-packages:
      - libgtksourceview-3.0-1
      - libgtkspell3-3-0
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libgucharmap-2-90-7
      - libsystemd0
      - libicu70 | libicu66
      - libpixman-1-0
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
apps:
  tpad:
    command: usr/bin/tpad
